LOG_FILE: "server.log"

GAME:
  GRAVITY: 9.8
  MAX_MOVES: 2
  MAX_REVIVED: 3

GAMEMAP:
  BEACH:
    SIZE_X: 1000
    SIZE_Y: 1000
    OBSTACLES: 10
    ENEMIES: 10
    GEMS: 8
    SILVER_COINS: 8
    GOLD_COINS: 3
  COLONIUS:
    SIZE_X: 1000
    SIZE_Y: 1000
    OBSTACLES: 10
    ENEMIES: 7
    GEMS: 3
    SILVER_COINS: 7
    GOLD_COINS: 3
  HOLIDAIUS:
    SIZE_X: 1000
    SIZE_Y: 1000
    OBSTACLES: 10
    ENEMIES: 10
    GEMS: 6
    SILVER_COINS: 5
    GOLD_COINS: 2


CHARACTER:
  INITIAL_X: 0
  INITIAL_Y: 0
  INITIAL_HEALTH: 100
  REVIVE_TIME: 10
  DAMAGE: 5
  MAX_REVIVED: 3
  MAX_MOVES_PER_CELL: 2
  RESPAWN_TIME: 15
  DAMAGE_TIME: 2
  INTOXICATED_TIME: 5
  JAZZ:
    SHOOT_COOLDOWN_TIME: 1
    HORIZONTAL_SPEED: 10
    VERTICAL_SPEED: 15
    SPRINT_SPEED: 20
    JUMP_HEIGHT: 5
  LORI:
    SHOOT_COOLDOWN_TIME: 1
    HORIZONTAL_SPEED: 10
    VERTICAL_SPEED: 15
    SPRINT_SPEED: 20
    JUMP_HEIGHT: 5
  SPAZ:
    SHOOT_COOLDOWN_TIME: 1
    HORIZONTAL_SPEED: 10
    VERTICAL_SPEED: 15
    SPRINT_SPEED: 20
    JUMP_HEIGHT: 5

WEAPON:
  BLASTER:
    BULLETS: 100
    DAMAGE: 10
    FIRE_RATE: 0.5
  BOUNCER:
    BULLETS: 100
    DAMAGE: 10
    FIRE_RATE: 0.5
  FREEZER:
    BULLETS: 100
    DAMAGE: 10
    FIRE_RATE: 0.5
  RFMISSILE:
    BULLETS: 100
    DAMAGE: 10
    FIRE_RATE: 0.5

OBSTACLE:
  MOVES: 50


ENEMY:
  WALKING:
    INITIAL_X: 0
    INITIAL_Y: 0
    INITIAL_HEALTH: 100
    DAMAGE: 1
    MAX_MOVES: 10
    MAX_REVIVED: 3
    DAMAGE_TIME: 2
    REVIVE_TIME: 5
    MAX_MOVES_PER_CELL: 2
    HIT_DISTANCE: 1
    HIT_DISTANCE_Y: 1
    VIEW_DISTANCE: 5
    VIEW_DISTANCE_HIT: 2
    GEM_DROP_PROB: 0.3
    BULLET_DROP_PROB: 0.5
    SILVER_COIN_DROP_PROB: 0.5
    GOLD_COIN_DROP_PROB: 0.1
    HEALTH_DROP_PROB: 0.2

  FLYING:
    INITIAL_X: 0
    INITIAL_Y: 0
    INITIAL_HEALTH: 150
    DAMAGE: 2
    MAX_MOVES: 10
    MAX_REVIVED: 3
    DAMAGE_TIME: 2
    REVIVE_TIME: 5
    MAX_MOVES_PER_CELL: 2
    HIT_DISTANCE: 1
    HIT_DISTANCE_Y: 1
    VIEW_DISTANCE: 5
    VIEW_DISTANCE_HIT: 2
    GEM_DROP_PROB: 0.3
    BULLET_DROP_PROB: 0.5
    SILVER_COIN_DROP_PROB: 0.5
    GOLD_COIN_DROP_PROB: 0.1
    HEALTH_DROP_PROB: 0.2

  JUMPING:
    INITIAL_X: 0
    INITIAL_Y: 0
    INITIAL_HEALTH: 200
    DAMAGE: 3
    MAX_MOVES: 10
    MAX_REVIVED: 3
    DAMAGE_TIME: 2
    REVIVE_TIME: 5
    MAX_MOVES_PER_CELL: 2
    HIT_DISTANCE: 1
    HIT_DISTANCE_Y: 1
    VIEW_DISTANCE: 5
    VIEW_DISTANCE_HIT: 2
    GEM_DROP_PROB: 0.3
    BULLET_DROP_PROB: 0.5
    SILVER_COIN_DROP_PROB: 0.5
    GOLD_COIN_DROP_PROB: 0.1
    HEALTH_DROP_PROB: 0.2
